export const S = {
  app: {
    minHeight: '100vh',
    background: 'linear-gradient(160deg,#0f0c29,#302b63,#24243e)',
    fontFamily: "'Nunito','Comic Sans MS',cursive,sans-serif",
    color: '#fff',
  },

  // Header
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '16px',
    flexWrap: 'wrap',
    gap: '12px',
  },
  title: { fontSize: '2rem', fontWeight: 900, color: '#FECA57', margin: 0 },
  subtitle: { color: '#ccc', margin: '4px 0 0', fontSize: '1rem' },
  headerRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexWrap: 'wrap',
  },
  scoreBadge: {
    background: '#FECA57',
    color: '#1a1a2e',
    borderRadius: '20px',
    padding: '8px 18px',
    fontWeight: 900,
    fontSize: '1.1rem',
  },

  // Buttons
  btn: {
    background: 'linear-gradient(135deg,#54A0FF,#5F27CD)',
    color: '#fff',
    border: 'none',
    borderRadius: '12px',
    padding: '11px 20px',
    fontSize: '0.95rem',
    fontWeight: 700,
    fontFamily: 'inherit',
    cursor: 'pointer',
  },
  printBtn: {
    background: 'linear-gradient(135deg,#FF9F43,#e55039)',
    color: '#fff',
    border: 'none',
    borderRadius: '12px',
    padding: '11px 18px',
    fontSize: '0.95rem',
    fontWeight: 700,
    fontFamily: 'inherit',
    cursor: 'pointer',
  },
  checkBtn: {
    background: 'linear-gradient(135deg,#1DD1A1,#00b894)',
    color: '#fff',
    border: 'none',
    borderRadius: '16px',
    padding: '16px 40px',
    fontSize: '1.2rem',
    fontWeight: 900,
    fontFamily: 'inherit',
    cursor: 'pointer',
  },

  // Top-level tabs (Math / Word Problems)
  mainTabs: { display: 'flex', gap: '10px', marginBottom: '14px' },
  mainTab: {
    background: 'rgba(255,255,255,0.05)',
    color: '#888',
    border: '2px solid rgba(255,255,255,0.12)',
    borderRadius: '12px',
    padding: '10px 22px',
    fontSize: '1rem',
    fontWeight: 700,
    fontFamily: 'inherit',
    cursor: 'pointer',
  },
  mainTabActive: {
    background: 'rgba(255,255,255,0.13)',
    color: '#fff',
    border: '2px solid rgba(255,255,255,0.4)',
  },

  // Mode filter tabs (Mixed / Addition / etc.)
  tabs: { display: 'flex', gap: '8px', flexWrap: 'wrap', marginBottom: '20px' },
  tab: {
    background: 'rgba(255,255,255,0.05)',
    color: '#888',
    border: '2px solid rgba(255,255,255,0.1)',
    borderRadius: '20px',
    padding: '7px 16px',
    fontSize: '0.9rem',
    fontWeight: 700,
    fontFamily: 'inherit',
    cursor: 'pointer',
  },
  tabActive: { background: 'rgba(255,255,255,0.1)' },

  // Math problem cards
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill,minmax(200px,1fr))',
    gap: '14px',
    marginBottom: '32px',
  },
  card: {
    border: '2px solid',
    borderRadius: '16px',
    padding: '18px',
    position: 'relative',
  },
  cardNum: {
    position: 'absolute',
    top: '10px',
    left: '12px',
    fontSize: '0.75rem',
    color: '#888',
    fontWeight: 700,
  },
  cardType: {
    position: 'absolute',
    top: '8px',
    right: '12px',
    fontSize: '1rem',
  },
  problem: {
    fontSize: '1.5rem',
    fontWeight: 900,
    color: '#fff',
    marginBottom: '12px',
    marginTop: '12px',
    textAlign: 'center',
  },
  input: {
    width: '100%',
    padding: '10px',
    borderRadius: '10px',
    border: '2px solid',
    background: 'rgba(255,255,255,0.08)',
    color: '#fff',
    fontSize: '1.3rem',
    fontWeight: 900,
    fontFamily: 'inherit',
    textAlign: 'center',
    outline: 'none',
    boxSizing: 'border-box',
  },
  feedback: {
    textAlign: 'center',
    marginTop: '8px',
    fontSize: '0.85rem',
    fontWeight: 700,
    color: '#1DD1A1',
  },

  // Word problem cards
  wordHint: { color: '#aaa', fontSize: '0.95rem', marginBottom: '16px' },
  wordGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    marginBottom: '32px',
  },
  wordCard: { border: '2px solid', borderRadius: '16px', padding: '18px 20px' },
  wordHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '10px',
  },
  wordNum: { fontSize: '0.85rem', color: '#888', fontWeight: 700 },
  wordTypeTag: {
    fontSize: '0.8rem',
    color: '#aaa',
    background: 'rgba(255,255,255,0.07)',
    borderRadius: '12px',
    padding: '3px 10px',
  },
  wordText: {
    fontSize: '1.05rem',
    lineHeight: 1.6,
    color: '#f0f0f0',
    marginBottom: '14px',
  },
  wordInputRow: { display: 'flex', alignItems: 'center', gap: '12px' },

  // Results
  actions: { textAlign: 'center', paddingBottom: '40px' },
  resultPanel: {
    background: 'rgba(255,255,255,0.07)',
    border: '2px solid rgba(255,255,255,0.15)',
    borderRadius: '20px',
    padding: '32px',
    display: 'inline-block',
    minWidth: '300px',
  },
  resultEmoji: { fontSize: '64px', marginBottom: '12px' },
  resultText: { fontSize: '1.1rem', fontWeight: 700, marginBottom: '8px' },
  resultScore: {
    fontSize: '1.5rem',
    fontWeight: 900,
    color: '#FECA57',
    marginBottom: '20px',
  },
}
